framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
        packages:
            app:
                json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
            admin:
                json_manifest_path: '%kernel.project_dir%/public/build/admin/manifest.json'
            site:
                json_manifest_path: '%kernel.project_dir%/public/build/site/manifest.json' 