twig:
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'
    globals:
        app_name: 'UTB Refonte'
        app_version: '1.0.0'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    paths:
        '%kernel.project_dir%/templates': ~
        '%kernel.project_dir%/src/Resources/views': ~
    date:
        format: 'Y-m-d'
        interval_format: '%%d days'
        timezone: 'Europe/Paris'
    number_format:
        decimals: 2
        decimal_point: '.'
        thousands_separator: ','
    strict_variables: '%kernel.debug%'

when@test:
    twig:
        strict_variables: true
        cache: false
