<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * droitClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class droitClientRepository extends EntityRepository {

    //verifie si le profil courant pe acceder a une action
    /**
     * Cette methode retourne un tableau au cas ou vous aviez les droits sur une action donnee
     * 
     * @param int $idprofil: identifiant du profil
     * @param int $idmodule: identifiant du module
     * @param int $idaction: identifiant de l'action 
     * @return boolean ou tableau des actions et droits sur module
     */
    public function verifAccess($idprofil, $idmodule, $idaction) {
        $droits = unserialize($this->findOneBy(array('profil' => $idprofil))->getDroits());
        //var_dump($droits);
        if (!array_key_exists($idmodule, $droits))
            return false;
        return in_array($idaction, $droits[$idmodule]);
    }

    /**
     * Cette methode retourne un tableau de droits relatifs a un profil
     * 
     * @param int $cond:  
     * @return array: Un tableau de droit client relatif a un profil
     */
    public function findProfil($cond) {
        $query = $this->_em->createQuery('SELECT d.id as iddroit FROM utbClientBundle:droitClient d INNER JOIN d.profil p WHERE p.id =:cond')
                ->setParameter('cond', $cond);


        return $query->getResult();
    }

}
