<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieCompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieCompteRepository extends EntityRepository {
    
   
    public function getAllCateg($locale, $page, $per_page) {

        $sql = ' SELECT c.codecategorie, c.libCategorie,c.active,c.sicarte,c.sicheque FROM   utbClientBundle:CategorieCompte c  ';
        $query = $this->_em->createQuery($sql);
        $query->setFirstResult(($page * $per_page) - $per_page);
        $query->setMaxResults($per_page);
        return $query->getResult();
    }
    
}
