<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteurRepository extends EntityRepository
{
    /**
     * Cette methode retourne la liste des comptes d'un abonne
     * 
     * @param int $idabonne : identifiant de l'abonne
     * @return array: tableau des comptes d'un abonne donne
     */
    public function getListeCompteurs($idabonne) {
        //$param = array();
        //Make a Select query
        $sql = 'SELECT  c.numeroCompteur, c.referenceClient,c.etatCompteur, c.quartier

                                                          
              FROM   utbClientBundle:Abonne a 
                     INNER JOIN a.compteurs c                     
              WHERE  a.id = :id  and c.etatCompteur = 1 and c.autoriseCompteur = 1';


        /** Fin parametres et valeur * */
        $query = $this->_em->createQuery($sql)
                ->setParameter('id', $idabonne);
        //var_dump($query);
        return $query->getResult();
    }    
    
    /**
     * Cette methode retourne la liste des comptes d'un abonne
     * 
     * @param int $idabonne : identifiant de l'abonne
     * @return array: tableau des comptes d'un abonne donne
     */
    public function getListeCompteursAdmin(): ?string {
        //$param = array();
        //Make a Select query
        $sql = 'SELECT  c.numeroCompteur, c.referenceClient,c.etatCompteur,c.quartier,a.nomPrenom

                                                          
              FROM   utbClientBundle:Abonne a 
                     INNER JOIN a.compteurs c                     
              WHERE  c.autoriseCompteur = 0';


        /** Fin parametres et valeur * */
        $query = $this->_em->createQuery($sql);
        //->setParameter('id', $idabonne);
        //var_dump($query);
        return $query->getResult();
    }
}
