<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DeviseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviseRepository extends EntityRepository {
    /**
     * Methode permettant de vor l'existence d'une devise locale
     * 
     * Intervient entre autres sur l'action listerubriqueAction du controlleur RubriqueController     
     */
    public function getTestDeviseLocale($islocale) {
        /* $query = $this->createQueryBuilder('rubrique')
          ->where('rubrique.nomRubrique = :nom')->setParameter('nom', $nom); */


        $query = $this->_em->createQuery('SELECT d  
                         FROM utbClientBundle:Devise d 
                         WHERE d.siLocale =:paramlocal AND d.affiche = 1')->setParameter('paramlocal', $islocale);

      /*  $query->setHint(
                \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
        );
        // Force the locale
        $query->setHint(
                \Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE, $locale
        ); 
     */
        return $query->getResult();
    }    
    
}
