<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * droitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class droitRepository extends EntityRepository {

    //verifie si le profil courant pe acceder a une action
    public function verifAccess($idprofil, $idmodule, $idaction) {
        $droits = unserialize($this->findOneBy(array('profil' => $idprofil))->getDroits());
        //var_dump($droits);
        if (!array_key_exists($idmodule, $droits))
            return false;
        return in_array($idaction, $droits[$idmodule]);
    }

    public function findProfil($cond) {
        $query = $this->_em->createQuery('SELECT d.id as iddroit FROM utbAdminBundle:droit d INNER JOIN d.profil p WHERE p.id =:cond')
                ->setParameter('cond', $cond);


        return $query->getResult();
    }

}
