<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FacturationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturationRepository extends EntityRepository {
    
}
