<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InfosAfterLoadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfosAfterLoadRepository extends EntityRepository {
    
}
